version: 2
updates:
  # 1. Update Ruby dependencies (Gemfile/gemspec) in the root
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    # Essential for gem projects without a Gemfile.lock:
    versioning-strategy: "increase"
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5
    groups:
      prod-safe-updates:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      dev-safe-updates:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # 2. Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    commit-message:
      prefix: chore
    groups:
      github-actions-updates:
        patterns:
          - "*"

  # 3. Update npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    groups:
      dev-dependencies:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
      prod-safe-updates:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"