inherit_gem:
  rubocop-govuk:
    - config/default.yml

AllCops:
  TargetRubyVersion: 2.7

Layout/HeredocIndentation:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false
