StylesPath = styles
Packages = https://github.com/alphagov/tech-docs-linter/releases/latest/download/tech-writing-style-guide.zip
SkippedScopes = pre, code, script, style
MinAlertLevel = suggestion
[*.{md,org,txt,erb,html}]

BasedOnStyles = tech-writing-style-guide
TokenIgnores = `[^`]+`

; full docs about vale.ini options are at https://vale.sh/docs/vale-ini