# Host to use for canonical URL generation (without trailing slash)
host: https://alphagov.github.io/tdt-documentation

# Header-related options
show_govuk_logo: false
service_name: Tech docs template
service_link: https://alphagov.github.io/tdt-documentation
phase: Beta

# Uncomment if you do not want to activate the GOV.UK Design System component extension
enable_govuk_components: true

# Links to show on right-hand-side of header
header_links:
  Template: https://github.com/alphagov/tech-docs-template
  Ruby gem: https://github.com/alphagov/tech-docs-gem
  Support: /support
footer_links:
  Accessibility: /accessibility/
  
# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 1

# Multi-page options
multipage_nav: true
collapsible_nav: true

# Show links to contribute on GitHub
show_contribution_banner: true
github_repo: https://github.com/alphagov/tech-docs-gem/documentation

# Enable search
enable_search: true

# Ownership for page reviews
default_owner_slack: '#gds-technical-writing'
owner_slack_workspace: gds

redirects:
  page-expiry.html: configure_project/page_expiry_and_review/#set-review-date-for-pages
  search.html: configure_project/global_configuration/#enable-search
  content.html: write_docs/content/#write-your-content
  create_new_project.html: create_project/create_new_project/#create-a-new-documentation-project
