name: 'Build middleman artifact'
on:
  workflow_call:
    inputs:
      upload-artifact:
        default: false
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: documentation
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'documentation/.nvmrc'
      - name: Setup Ruby
        uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          bundler-cache: true
          working-directory: documentation
          ruby-version: '3'
      - name: Install gems
        run: bundle install
      - name: Build
        run: bundle exec middleman build
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v4.1.3
        if: ${{ inputs.upload-artifact }}
        with:
          name: build
          path: documentation/build/**
          retention-days: 1
