name: check-documentation-updates

on:
  workflow_call:
    outputs:
      documentation-updated:
        value: ${{ jobs.check-documentation-updates.outputs.documentation-updated }}


jobs:
  check-documentation-updates:
    runs-on: ubuntu-latest
    outputs:
      documentation-updated: ${{ steps.documentation_updated.outputs.documentation-updated }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          show-progress: false

      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          ruby-version: '3'

      - name: Documentation updated
        id: documentation_updated
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^documentation/'; then
            echo "documentation-updated=true" >> $GITHUB_OUTPUT
          else
            echo "documentation-updated=false" >> $GITHUB_OUTPUT
          fi
