name: Publish

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency: rubygems

jobs:
  pre:
    name: Pre-flight checks
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.gem_version.outputs.new_version }}

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1

      - name: Check if new version to release
        id: gem_version
        run: |
          gem_version=$(ruby -r rubygems -e "puts Gem::Specification::load('govuk_tech_docs.gemspec').version")
          echo "::set-output name=gem_version::$gem_version"

          if git fetch origin "refs/tags/v$gem_version" >/dev/null 2>&1
          then
            echo "Tag 'v$gem_version' already exists"
            echo "::set-output name=new_version::false"
          else
            echo "::set-output name=new_version::true"
          fi

  deploy:
    name: Publish Ruby Gem
    environment: rubygems
    permissions:
      contents: write  # needed to be able to tag the release
    runs-on: ubuntu-latest
    needs: pre
    if: ${{ needs.pre.outputs.go == 'true' }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '14'

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Publish
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p ~/.gem

          cat << EOF > ~/.gem/credentials
          ---
          :rubygems_api_key: ${RUBYGEMS_API_KEY}
          EOF

          chmod 0600 ~/.gem/credentials

          # tag will be associated with github-actions bot user, see
          # https://github.community/t/github-actions-bot-email-address/17204
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          bundle exec rake release
