name: Test

on:
  workflow_call:

permissions:
  contents: read          # Allows the action to check out your repository code
  pull-requests: write    # Allows the action to comment on or update the Dependabot PR
  statuses: write         # Allows the action to post pass/fail build statuses

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1
      matrix:
        ruby: ['3.3', '3.4', '4.0']

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - uses: ruby/setup-ruby@003a5c4d8d6321bd302e38f6f0ec593f77f06600 # v1.319.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Lint Ruby and javascript files
        run: bundle exec rake lint

      - name: Run Ruby unit tests
        run: bundle exec rake spec

      - name: Run Javascript tests
        run: bundle exec rake jasmine:ci
